# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xpol/setup-lua@v0.2
      - uses: leafo/gh-actions-luarocks@v3
      - name: test
        run: |
          luarocks install busted \
          && luarocks install net-url \
          && luarocks install luacov \
          && busted -c \
          && bash <(curl -s https://codecov.io/bash)
        env: 
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}